# config.yaml

symbols:
  - USDJPY

timeframes:
  - M5

bars_list:
  - 100000

# 保存先ルートパス（環境自動切替対応）
data_root_local: C:/Projects/project_10k_to_1m_data
data_root_colab: project_10k_to_1m_data  # Google Drive の MyDrive 直下に置く想定

tp_default: 140
sl_default: 10
