# project_10k_to_1m/config.yaml

# ── プロジェクト & データ基本設定 ──────────────────────────────
project_base: "."                         # スクリプトルート
data_base:    "../project_10k_to_1m_data"  # データリポジトリ

mt5_data_dir:  "${data_base}/raw"        # MT5 からダウンロード済みの生データ置き場
processed_dir: "${data_base}/processed"  # 特徴量生成／ラベル付与後のデータ置き場
model_dir:     "${data_base}/models"     # 学習済みモデル保管場所
report_dir:    "${data_base}/reports"    # 各種レポート出力先

# ── テスト対象通貨ペア & 条件 ─────────────────────────────────
symbol:    "USDJPY"    # 通貨ペア（MT5 のファイル名と合わせる）
timeframe: "H1"        # 時間足（例: M5, M15, H1, H4 など）
bars:      100000      # 使用するバー数

# ── バックテスト & モデル評価 パラメータ ────────────────────────
tp:        140.0   # テイクプロフィット(pips)
sl:        10.0   # ストップロス(pips)

spread:      3 # スプレッド(pips換算)
commission:  0  # 手数料(pips換算)
slippage:    10  # スリッページ(pips換算)
