# project_root/config.yaml

# ─── ディレクトリ設定 ──────────────────────────────────────
# project_root/config.yaml

# ─── データベースパス（ローカル／Colab 用を両方定義）──────────
data_base_local: "C:/Projects/project_10k_to_1m_data"
data_base_colab: "/content/drive/MyDrive/project_10k_to_1m_data"

# 現状はローカル向けを参照
data_base: "${data_base_local}"

# ─── 各ディレクトリは必ず "${data_base}/…" の形式で書く──────────
mt5_data_dir: "${data_base}/raw"
processed_dir: "${data_base}/processed"
model_dir: "${processed_dir}/models"
report_dir: "${processed_dir}/reports"

# ─── 通貨ペア／時間軸／データ本数 ─────────────────────────
symbol: "USDJPY"
timeframe: "M5"
bars: 100000

# ─── ラベル生成パラメータ ─────────────────────────────────
label_gen:
  tp: 140
  sl: 10
  exclude_before_release: true
  release_exclude_window_mins: 30

# ─── 生データ命名ルール ───────────────────────────────────
raw_data:
  date_format: "%Y%m%d"

# ─── 実行フェーズ制御（run_pipeline.py 用）──────────────────
run_phases: [1,2,3,4]

# ─── MT5 接続設定 ────────────────────────────────────────
mt5:
  path: "C:\\Program Files\\MetaTrader 5\\terminal64.exe"
  login: 70042530
  password: 2090XM_torihiki
