# project_10k_to_1m/paper_trade/config.yaml

mt5:
  symbol: "USDJPY"
  timeframe: "M5"
  login: 70042530
  password: 2090XM_torihiki
  server: XMTrading-MT5 3
  path: "C:\\Program Files\\MetaTrader 5\\terminal64.exe"
  timezone: "Asia/Tokyo"

trade:
  lot_size: 0.1
  spread_pips: 2.5
  slippage_pips: 1.0

model:
  path: "..C:/Projects/project_10k_to_1m_data/processed/USDJPY/M5/xgb_model_USDJPY_M5_100000_*.pkl"
  threshold_long: 0.55
  threshold_short: 0.40

features:
  atr_window: 14
  rsi_window: 14
  ma_window: 20
  shap_sample_size: 100
  shap_threshold: 0.80

output:
  signal_csv: "paper_trade/signals.csv"
  log_file: "paper_trade/mt5watch.log"

#webhook:
#  slack_url: "https://hooks.slack.com/services/XXXX/XXXX/XXXX"
#  timeout_seconds: 5
#  retry_count: 3
#  error_notify_channel: "#alerts"

logging:
  level: "INFO"
  max_bytes: 10485760
  backup_count: 5
